#!/usr/bin/env python3
"""
Generate SQL import script for BOG USD transactions from Excel
Converts Excel to SQL INSERT statements that can be run directly on Supabase
"""

import pandas as pd
from datetime import datetime, timedelta
from pathlib import Path

def excel_date_to_date(excel_date):
    """Convert Excel serial date to Python datetime"""
    if pd.isna(excel_date):
        return None
    try:
        return datetime(1900, 1, 1) + timedelta(days=excel_date - 2)
    except:
        return None

def sql_escape_string(s):
    """Escape string for SQL"""
    if s is None or pd.isna(s):
        return "NULL"
    s = str(s).replace("'", "''")
    return f"'{s}'"

def sql_escape_number(n):
    """Escape number for SQL"""
    if n is None or pd.isna(n):
        return "NULL"
    return str(n)

def sql_escape_date(d):
    """Escape date for SQL"""
    if d is None or pd.isna(d):
        return "NULL"
    if isinstance(d, datetime):
        return f"'{d.strftime('%Y-%m-%d')}'"
    if isinstance(d, (int, float)):
        dt = excel_date_to_date(d)
        if dt:
            return f"'{dt.strftime('%Y-%m-%d')}'"
    return "NULL"

def main():
    print("=" * 100)
    print("GENERATING SQL IMPORT SCRIPT")
    print("=" * 100)
    
    file_path = r'Chrome Logs\BOG USD 2018-2022.xlsx'
    
    if not Path(file_path).exists():
        print(f"❌ File not found: {file_path}")
        return 1
    
    # Load Excel data
    print(f"\n✓ Loading Excel file: {file_path}")
    df = pd.read_excel(file_path, sheet_name='Sheet1')
    print(f"✓ Loaded {len(df):,} rows")
    
    # Column mapping
    column_mapping = {
        'transaction_date': 'თარიღი',
        'document_number': 'საბუთის N',
        'correspondent_account': 'მოკორესპოდენტო ანგარიში',
        'debit_amount': 'დებეტი',
        'credit_amount': 'კრედიტი',
        'exchange_rate': 'კურსი',
        'debit_gel': 'დებეტი ექვ ლარში',
        'credit_gel': 'კრედიტი ექვ ლარში',
        'operation_description': 'ოპერაციის შინაარსი',
        'operation_type': 'ოპერაციის ტიპი',
        'operation_id': 'ოპერაციის იდ',
        'ref': 'Ref',
        'sender_name': 'გამგზავნის დასახელება',
        'sender_inn': 'გამგზავნის საიდენტიფიკაციო კოდი',
        'sender_account': 'გამგზავნის ანგარიშის ნომერი',
        'sender_bank_code': 'გამგზავნი ბანკის კოდი',
        'sender_bank_name': 'გამგზავნი ბანკის დასახელება',
        'beneficiary_name': 'მიმღების დასახელება',
        'beneficiary_inn': 'მიმღების საიდენტიფიკაციო კოდი',
        'beneficiary_account': 'მიმღების ანგარიშის ნომერი',
        'beneficiary_bank_code': 'მიმღები ბანკის კოდი',
        'beneficiary_bank_name': 'მიმღები ბანკის დასახელება',
        'purpose': 'დანიშნულება',
        'additional_info': 'დამატებითი ინფორმაცია',
        'amount': 'თანხა',
        'amount_gel': 'თანხა ექვ ლარში',
    }
    
    # Generate SQL script
    output_file = '_bog_usd_import.sql'
    
    print(f"\n✓ Generating SQL INSERT statements...")
    
    with open(output_file, 'w', encoding='utf-8') as f:
        # Header comment
        f.write('-- BOG USD Transaction Import Script\n')
        f.write('-- Generated by _generate_bog_usd_sql.py\n')
        f.write(f'-- Date: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}\n')
        f.write(f'-- Total rows: {len(df):,}\n\n')
        
        # Get list of columns
        db_columns = list(column_mapping.keys())
        excel_columns = [column_mapping[col] for col in db_columns]
        
        f.write('-- Insert transaction data\n')
        cols_str = ', '.join([f'"{col}"' for col in db_columns])
        f.write(f'INSERT INTO "GE78BG0000000893486000_BOG_USD" ({cols_str})\n')
        f.write('VALUES\n')
        
        # Generate INSERT rows
        row_count = 0
        for idx, row in df.iterrows():
            values = []
            for excel_col, data_type in zip(excel_columns, db_columns):
                val = row[excel_col]
                
                # Type-specific handling
                if data_type == 'transaction_date':
                    values.append(sql_escape_date(val))
                elif data_type in ['debit_amount', 'credit_amount', 'exchange_rate', 'debit_gel', 
                                   'credit_gel', 'amount', 'amount_gel', 'sender_inn', 'beneficiary_inn']:
                    values.append(sql_escape_number(val))
                else:
                    values.append(sql_escape_string(val))
            
            # Write row
            values_str = ', '.join(values)
            row_count += 1
            
            if idx < len(df) - 1:
                f.write(f'  ({values_str}),\n')
            else:
                f.write(f'  ({values_str})\n')
            
            if row_count % 100 == 0:
                print(f'  ✓ Generated {row_count:,} rows')
        
        f.write('ON CONFLICT (operation_id) DO NOTHING;\n\n')
        
        # Add summary comment
        f.write(f'-- Import completed: {row_count:,} rows inserted\n')
        f.write(f'-- Check table row count with: SELECT COUNT(*) FROM "GE78BG0000000893486000_BOG_USD";\n')
    
    print(f"\n✓ SQL script generated: {output_file}")
    print(f"✓ Total INSERT rows: {row_count:,}")
    
    # Get file size
    file_size_mb = Path(output_file).stat().st_size / (1024 * 1024)
    print(f"✓ File size: {file_size_mb:.2f} MB")
    
    print(f"\n{'=' * 100}")
    print("IMPORT INSTRUCTIONS")
    print(f"{'=' * 100}")
    print(f"""
1. Open Supabase Console:
   URL: https://app.supabase.com/project/fojbzghphznbslqwurrm/sql/new

2. Copy all content from: {output_file}

3. Paste into the SQL Editor in Supabase

4. Click "Run" button to execute the import

5. Verify the import with:
   SELECT COUNT(*) as total_rows FROM "GE78BG0000000893486000_BOG_USD";
   SELECT MIN(transaction_date) as min_date, MAX(transaction_date) as max_date 
   FROM "GE78BG0000000893486000_BOG_USD" WHERE transaction_date IS NOT NULL;

Alternative: Use psql command line:
   psql -h db.fojbzghphznbslqwurrm.supabase.co -U postgres -d postgres -f {output_file}
    """)
    
    return 0

if __name__ == '__main__':
    exit(main())
