CREATE TABLE "tbc_gel_raw_6050100002" (
  "id" BIGSERIAL PRIMARY KEY,
  "uuid" UUID NOT NULL,

  -- Record fields
  "date" TEXT,
  "paid_in" TEXT,
  "paid_out" TEXT,
  "balance" TEXT,
  "description" TEXT,
  "additional_information" TEXT,
  "additional_description" TEXT,
  "transaction_type" TEXT,
  "document_date" TEXT,
  "document_number" TEXT,
  "partner_account_number" TEXT,
  "partner_name" TEXT,
  "partner_bank_code" TEXT,
  "partner_bank_name" TEXT,
  "operation_code" TEXT,
  "partner_tax_code" TEXT,
  "taxpayer_code" TEXT,
  "taxpayer_name" TEXT,
  "transaction_id" TEXT,

  -- Parsing columns (same as BOG raw)
  "import_batch_id" TEXT,
  "import_date" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  "counteragent_processed" BOOLEAN DEFAULT false NOT NULL,
  "counteragent_found" BOOLEAN DEFAULT false NOT NULL,
  "counteragent_missing" BOOLEAN DEFAULT false NOT NULL,
  "parsing_rule_processed" BOOLEAN DEFAULT false NOT NULL,
  "parsing_rule_applied" BOOLEAN DEFAULT false NOT NULL,
  "parsing_rule_conflict" BOOLEAN DEFAULT false NOT NULL,
  "payment_id_processed" BOOLEAN DEFAULT false NOT NULL,
  "payment_id_matched" BOOLEAN DEFAULT false NOT NULL,
  "payment_id_conflict" BOOLEAN DEFAULT false NOT NULL,
  "counteragent_inn" TEXT,
  "applied_rule_id" INTEGER,
  "processing_case" TEXT,
  "is_processed" BOOLEAN DEFAULT false NOT NULL,
  "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
