-- Auto-generated structural constraints from data_validation_spec.xlsx
ALTER TABLE "Counteragents" ALTER COLUMN "Timestamp" SET NOT NULL;
ALTER TABLE "Counteragents" ALTER COLUMN "Name" SET NOT NULL;
ALTER TABLE "Counteragents" ALTER COLUMN "Sex" SET NOT NULL;
ALTER TABLE "Counteragents" ALTER COLUMN "Entity Type" SET NOT NULL;
ALTER TABLE "Counteragents" ALTER COLUMN "Pension Scheme" SET NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS "uq_Counteragents_Tax ID" ON "Counteragents"("Tax ID");
ALTER TABLE "Counteragents" ALTER COLUMN "Country" SET NOT NULL;
ALTER TABLE "Counteragents" ALTER COLUMN "Counteragent UUID" SET NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS "uq_Counteragents_Counteragent UUID" ON "Counteragents"("Counteragent UUID");
ALTER TABLE "Counteragents" ADD CONSTRAINT "fk_Counteragents_Counteragent UUID_Counteragents_Counteragent UUID" FOREIGN KEY ("Counteragent UUID") REFERENCES "Counteragents"("Counteragent UUID");
ALTER TABLE "Counteragents" ALTER COLUMN "Date of incorporation or birth" SET NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS "uq_Counteragents_ORIS ID :" ON "Counteragents"("ORIS ID :");
ALTER TABLE "Counteragents" ALTER COLUMN "Internal No" SET NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS "uq_Counteragents_Internal No" ON "Counteragents"("Internal No");
ALTER TABLE "Counteragents" ALTER COLUMN "Counteragent" SET NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS "uq_Counteragents_Counteragent" ON "Counteragents"("Counteragent");
ALTER TABLE "Counteragents" ALTER COLUMN "Country UUID" SET NOT NULL;
ALTER TABLE "Counteragents" ALTER COLUMN "Entity Type UUID" SET NOT NULL;
ALTER TABLE "Countries" ALTER COLUMN "Timestamp" SET NOT NULL;
ALTER TABLE "Countries" ALTER COLUMN "Country UUID" SET NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS "uq_Countries_Country UUID" ON "Countries"("Country UUID");
ALTER TABLE "Countries" ADD CONSTRAINT "fk_Countries_Country UUID_Countries_Country UUID" FOREIGN KEY ("Country UUID") REFERENCES "Countries"("Country UUID");
ALTER TABLE "Countries" ALTER COLUMN "Country Name English" SET NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS "uq_Countries_Country Name English" ON "Countries"("Country Name English");
ALTER TABLE "Countries" ALTER COLUMN "Country Name Georgian" SET NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS "uq_Countries_Country Name Georgian" ON "Countries"("Country Name Georgian");
ALTER TABLE "Countries" ALTER COLUMN "ISO 2" SET NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS "uq_Countries_ISO 2" ON "Countries"("ISO 2");
ALTER TABLE "Countries" ALTER COLUMN "ISO 3" SET NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS "uq_Countries_ISO 3" ON "Countries"("ISO 3");
ALTER TABLE "Countries" ALTER COLUMN "UN Code" SET NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS "uq_Countries_UN Code" ON "Countries"("UN Code");
ALTER TABLE "Countries" ALTER COLUMN "Country" SET NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS "uq_Countries_Country" ON "Countries"("Country");
ALTER TABLE "Entity Types" ALTER COLUMN "Timestamp" SET NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS "uq_Entity Types_Timestamp" ON "Entity Types"("Timestamp");
ALTER TABLE "Entity Types" ALTER COLUMN "Entity Type UUID" SET NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS "uq_Entity Types_Entity Type UUID" ON "Entity Types"("Entity Type UUID");
ALTER TABLE "Entity Types" ADD CONSTRAINT "fk_Entity Types_Entity Type UUID_Entity Types_Entity Type UUID" FOREIGN KEY ("Entity Type UUID") REFERENCES "Entity Types"("Entity Type UUID");
ALTER TABLE "Entity Types" ALTER COLUMN "Entity Type Name" SET NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS "uq_Entity Types_Entity Type Name" ON "Entity Types"("Entity Type Name");