/**
 * Maps Lucide icon names (as stored in UserNavItem.icon / UserNavFolder.icon)
 * to Unicode emoji suitable for browser tab titles.
 * Returns '' for unmapped names so the title is left unchanged.
 */
const ICON_EMOJI_MAP: Record<string, string> = {
  // Navigation & Layout
  Home: '🏠',
  LayoutGrid: '⊞',
  LayoutDashboard: '📊',
  Sidebar: '▤',
  PanelLeft: '◧',
  Columns2: '⫿',
  Rows2: '☰',

  // Folders & Files
  Folder: '📁',
  FolderOpen: '📂',
  FolderPlus: '📁',
  FolderTree: '📁',
  File: '📄',
  FileText: '📄',
  FileBarChart2: '📊',
  FileSpreadsheet: '📊',
  FileCheck: '✅',
  FileImage: '🖼️',
  FilePlus: '📄',
  FileMinus: '📄',
  FileSearch: '🔍',
  FileX: '❌',
  FileCode: '📄',

  // Finance & Business
  Landmark: '🏛️',
  Wallet: '👛',
  Wallet2: '👛',
  Banknote: '💵',
  DollarSign: '💵',
  Coins: '🪙',
  CreditCard: '💳',
  Receipt: '🧾',
  ReceiptText: '🧾',
  PiggyBank: '🐷',
  BadgeDollarSign: '💰',
  BadgePercent: '🏷️',
  Percent: '%',
  TrendingUp: '📈',
  TrendingDown: '📉',
  ArrowLeftRight: '↔️',
  Scale: '⚖️',
  Calculator: '🧮',
  Sigma: 'Σ',

  // Charts & Analytics
  BarChart3: '📊',
  BarChart2: '📊',
  LineChart: '📈',
  ChartPie: '🥧',
  ChartArea: '📈',
  ChartNoAxesColumn: '📊',
  ChartCandlestick: '📊',
  Activity: '📈',
  Gauge: '🔢',

  // People & Organizations
  Users: '👥',
  Users2: '👥',
  UserCheck: '👤',
  UserPlus: '👤',
  UserMinus: '👤',
  UserX: '👤',
  UserCog: '👤',
  CircleUser: '👤',
  Contact: '📇',
  PersonStanding: '🧍',
  HeartHandshake: '🤝',
  BadgeCheck: '✅',

  // Buildings & Places
  Building2: '🏢',
  Building: '🏛️',
  Factory: '🏭',
  Hotel: '🏨',
  Store: '🏪',
  Warehouse: '🏭',
  MapPin: '📍',
  Map: '🗺️',
  Globe: '🌐',
  Globe2: '🌍',
  Compass: '🧭',
  Route: '🛣️',
  Navigation: '🧭',
  Mountain: '⛰️',
  TreePine: '🌲',

  // Communication
  Mail: '✉️',
  MailOpen: '📬',
  Send: '📨',
  MessageSquare: '💬',
  MessageCircle: '💬',
  Phone: '📞',
  PhoneCall: '📞',
  Bell: '🔔',
  BellOff: '🔕',
  BellRing: '🔔',
  Inbox: '📥',
  AtSign: '@',
  Link: '🔗',
  Share2: '↗️',

  // Documents & Clipboard
  BookOpen: '📖',
  BookMarked: '📚',
  ClipboardList: '📋',
  ClipboardCheck: '✅',
  ClipboardX: '❌',
  Paperclip: '📎',
  Copy: '📋',
  Printer: '🖨️',
  Archive: '📦',
  Bookmark: '🔖',

  // Tags & Categorization
  Tag: '🏷️',
  Hash: '#',
  Star: '⭐',
  Flag: '🚩',
  Pin: '📌',
  Layers2: '🗂️',
  Layers: '📚',

  // Alerts & Status
  Info: 'ℹ️',
  HelpCircle: '❓',
  AlertCircle: '⚠️',
  AlertTriangle: '⚠️',
  CheckCircle: '✅',
  XCircle: '❌',
  ShieldCheck: '🛡️',
  ShieldOff: '🛡️',
  Lock: '🔒',
  Key: '🔑',
  Eye: '👁️',
  EyeOff: '🙈',

  // Actions & Operations
  Search: '🔍',
  Filter: '🔽',
  SortAsc: '↑',
  SortDesc: '↓',
  RefreshCcw: '🔄',
  Download: '⬇️',
  Upload: '⬆️',
  Plus: '➕',
  Check: '✔️',
  Zap: '⚡',
  Power: '⏻',
  Wrench: '🔧',
  Settings: '⚙️',
  Settings2: '⚙️',
  Sliders: '🎛️',
  History: '🕐',
  Clock: '🕐',
  Calendar: '📅',
  CalendarCheck: '📅',
  CalendarDays: '📅',
  Timer: '⏱️',
  Watch: '⌚',

  // Shopping & Commerce
  ShoppingCart: '🛒',
  ShoppingBag: '🛍️',
  Package: '📦',
  Package2: '📦',
  Box: '📦',
  Truck: '🚛',
  Plane: '✈️',
  Ship: '🚢',

  // Tech & Systems
  Database: '🗄️',
  Server: '🖥️',
  Monitor: '🖥️',
  Laptop: '💻',
  Smartphone: '📱',
  Cpu: '⚙️',
  HardDrive: '💾',
  Wifi: '📶',
  Cloud: '☁️',
  CloudUpload: '☁️',
  CloudDownload: '☁️',
  Code: '🔤',
  Code2: '🔤',
  Terminal: '⌨️',
  QrCode: '📱',

  // Media & Visuals
  Image: '🖼️',
  Camera: '📷',
  Video: '🎥',
  Film: '🎬',
  Music: '🎵',
  Headphones: '🎧',
  Podcast: '🎙️',
  Radio: '📻',

  // Tree / Network
  ListTree: '🌿',
  Network: '🔗',

  // Misc / Extra
  Leaf: '🌿',
  Sparkles: '✨',
  Trophy: '🏆',
  Crown: '👑',
  Award: '🏅',
  Gift: '🎁',
  Briefcase: '💼',
  Palette: '🎨',
  Pencil: '✏️',
  Scissors: '✂️',
  Ruler: '📏',
  Flame: '🔥',
  Target: '🎯',
  LogIn: '🔑',
  LogOut: '🚪',
  Moon: '🌙',
  Sun: '☀️',
  Thermometer: '🌡️',
  Droplets: '💧',
  Radar: '📡',
};

export function iconToEmoji(iconName: string | null | undefined): string {
  if (!iconName) return '';
  return ICON_EMOJI_MAP[iconName] ?? '';
}
