name: CI
on:
  push: { branches: [main, dev] }
  pull_request: { branches: [main, dev] }
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 20, cache: npm }
      - run: npm ci
      - run: npx prisma generate
      - name: Build
        env:
          NEXTAUTH_URL: http://localhost:3000
          NEXTAUTH_SECRET: dummy_secret_for_ci
          GOOGLE_CLIENT_ID: dummy
          GOOGLE_CLIENT_SECRET: dummy
          DATABASE_URL: postgresql://user:pass@localhost:5432/ci?schema=public
        run: npm run build --if-present
      - run: npm run lint --if-present
      - run: npm test --if-present
